server:
  port: 2020
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  mvc:
    view:
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: local
