server:
  port: 2020
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/VetClinic?serverTimezone=UTC
    username: admin
    password: vetclinic23
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
